#!/bin/bash

#if [ `wmctrl -l | grep -c "scratchpad"` = 0 ]
#then
#    alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad
#fi

case $BLOCK_BUTTON in
    1) # Left Click
        # i3-msg exec --no-startup-id "raiseorlaunch -r -t "scratchpad" -e '--no-startup-id alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad'" > /dev/null
        # i3-msg exec "raiseorlaunch -r -t scratchpad -e 'alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad'"
        i3-msg --quiet "exec --no-startup-id raiseorlaunch -r -t scratchpad -e '--no-startup-id alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad'"
        ;;
    2) # Middle Click
        i3-msg --no-startup-id exec "kill"
        ;;
    3) # Right Click
        i3-msg --no-startup-id exec "kill"
        ;;
esac

dbm=$(wmctrl -l | grep -c "scratchpad")
COLOR_on="#e06c75"
COLOR_off="#abb2bf"

if [[ $dbm -eq 0 ]]
then
   # i3-msg exec "alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad" > /dev/nul
    echo "<span color='$COLOR_off'>  Vim</span>"
else
    echo "<span color='$COLOR_on'>  Vim</span>"
fi

