#!/bin/bash

#if [ `wmctrl -l | grep -c "scratchpad"` = 0 ]
#then
#    alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad
#fi

dbm=$(wmctrl -l | grep -c "scratchpad")
COLOR_on="#e06c75"
COLOR_off="#abb2bf"

if [[ $dbm -eq 0 ]]
then
   # i3-msg exec "alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad" > /dev/nul
    echo "<span color='$COLOR_off'>  Vim</span>"
else
    echo "<span color='$COLOR_on'>  Vim</span>"
fi

